channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=23.2.1
- pip:
  - mlflow==2.18.0
  - attrs==23.1.0
  - cffi==2.0.0
  - cloudpickle==3.1.2
  - defusedxml==0.7.1
  - ipython==8.18.1
  - numpy==1.26.1
  - pandas==2.2.2
  - psutil==5.9.6
  - scikit-learn==1.4.2
  - scipy==1.13.0
  - tensorflow==2.16.1
name: mlflow-env
